---
# Web server specific variables
nginx_user: www-data
web_root: /var/www/html
php_version: "7.4"
php_modules:
  - php7.4-fpm
  - php7.4-mysql
  - php7.4-cli
  - php7.4-curl
  - php7.4-gd
  - php7.4-mbstring
  - php7.4-xml
  - php7.4-zip
